import puppeteer, { type Browser } from "puppeteer";
import { putObjectBuffer } from "./storage";

// Unit 12/19/21's long-deferred Open Question, closed here — a single
// headless Chromium instance shared across jobs (launching per-PDF would be
// far too slow), rendering plain server-built HTML to PDF. No client-side
// JS in the rendered documents; everything is server-interpolated data.
let browserPromise: Promise<Browser> | null = null;

async function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    browserPromise = puppeteer.launch({ headless: true, args: ["--no-sandbox", "--disable-setuid-sandbox"] });
  }
  return browserPromise;
}

export async function renderHtmlToPdf(html: string): Promise<Buffer> {
  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({ format: "A4", printBackground: true, margin: { top: "16mm", bottom: "16mm", left: "12mm", right: "12mm" } });
    return Buffer.from(pdf);
  } finally {
    await page.close();
  }
}

/** Renders HTML to PDF and uploads it under the given S3 key — the key (not a public URL) is what gets stored in a `pdfUrl` column, resolved to a signed URL on read (same convention as Unit 50's `Document.key`). */
export async function renderAndUploadPdf(key: string, html: string): Promise<string> {
  const pdf = await renderHtmlToPdf(html);
  return putObjectBuffer(key, pdf, "application/pdf");
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

/** Shared page shell — header (branch name/logo), body, footer — every PDF in this worker uses this so they look like one system, not three ad-hoc templates. */
export function pdfShell(opts: { branchName: string; logoUrl?: string | null; title: string; bodyHtml: string }): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; color: #1a1a1a; margin: 0; padding: 0; }
  .header { display: flex; align-items: center; gap: 12px; border-bottom: 2px solid #4F46E5; padding-bottom: 12px; margin-bottom: 20px; }
  .header img { height: 48px; width: 48px; object-fit: contain; }
  .header h1 { font-size: 18px; margin: 0; }
  .title { font-size: 14px; color: #4F46E5; font-weight: 600; margin: 0 0 16px; text-transform: uppercase; letter-spacing: 0.05em; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
  th { background: #f5f5f7; }
  .meta { font-size: 12px; color: #555; margin-bottom: 12px; }
  .meta span { margin-right: 24px; }
  .footer { margin-top: 32px; font-size: 10px; color: #999; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    ${opts.logoUrl ? `<img src="${escapeHtml(opts.logoUrl)}" />` : ""}
    <h1>${escapeHtml(opts.branchName)}</h1>
  </div>
  <p class="title">${escapeHtml(opts.title)}</p>
  ${opts.bodyHtml}
  <div class="footer">Generated by Vidyut</div>
</body>
</html>`;
}

export { escapeHtml };
