packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@sentry/cli': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react-native@1.37.0
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - argon2
  - esbuild
  - msgpackr-extract
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
