export { prisma } from "./client";
export { withTenant } from "./with-tenant";
export { seedDefaultRoles } from "./seed-roles";
export { seedModuleToggles } from "./seed-modules";
export { nextAdmissionNo } from "./generate-admission-no";
export { getCurrentSessionId } from "./current-session";
export { nextInvoiceNumber, nextReceiptNumber } from "./generate-invoice-number";
export { generateSchoolCode } from "./generate-school-code";
export { nextCertificateNumber } from "./generate-certificate-number";
export { nextPlatformInvoiceNumber } from "./generate-platform-invoice-number";
export * from "@prisma/client";
