import type { Permission } from "./permissions";

/** context/data-model.md §3 — RoleKey enum (mirrored in the Prisma schema). */
export const ROLE_KEYS = [
  "SUPERADMIN",
  "OWNER",
  "PRINCIPAL",
  "ADMIN",
  "ACCOUNTANT",
  "TEACHER",
  "PARENT",
  "STUDENT",
  // Unit 36 — one tenant-created custom role per tenant (role.manage).
  // ponytail: a single shared enum value means at most one custom role per
  // tenant today (the `@@unique([tenantId, key])` constraint on Role would
  // otherwise need to change); upgrade path if a school needs more than one:
  // switch Role.key to a free-form string and re-key uniqueness on name.
  "CUSTOM",
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

/** Staff/admin roles that go through the permission grid (context/rbac.md). */
export type StaffRoleKey = "OWNER" | "PRINCIPAL" | "ADMIN" | "ACCOUNTANT" | "TEACHER";

/**
 * Default permission grid for seeded system roles — transcribed verbatim
 * from the context/rbac.md matrix. Used to seed RolePermission per tenant;
 * owners can edit their tenant's copy afterwards.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<StaffRoleKey, Permission[]> = {
  OWNER: [
    "branch.manage",
    "session.manage",
    "settings.manage",
    "user.manage",
    "role.manage",
    "student.view",
    "student.edit",
    "student.import",
    "student.delete",
    "guardian.manage",
    "admission.manage",
    "staff.manage",
    "leave.apply",
    "leave.approve",
    "class.manage",
    "subject.manage",
    "timetable.manage",
    "attendance.view",
    "attendance.regularize",
    "exam.manage",
    "marks.moderate",
    "reportcard.generate",
    "reportcard.publish",
    "fee.setup",
    "fees.collect",
    "fee.view",
    "fee.concession.approve",
    "fee.refund",
    "fee.reports",
    "certificate.issue",
    "announcement.send",
    "notification.send",
    "engagement.manage",
    "dashboard.owner",
    "dashboard.principal",
    "subscription.view",
    "transport.manage",
    "library.manage",
    "hostel.manage",
    "frontoffice.manage",
    "wellbeing.manage",
    "accounting.manage",
    "payroll.manage",
    "inventory.manage",
    "task.manage",
    "lms.manage",
  ],
  PRINCIPAL: [
    "session.manage",
    "settings.manage",
    "student.view",
    "student.edit",
    "student.import",
    "guardian.manage",
    "admission.manage",
    "staff.manage",
    "leave.apply",
    "leave.approve",
    "class.manage",
    "subject.manage",
    "timetable.manage",
    "attendance.mark",
    "attendance.view",
    "attendance.regularize",
    "exam.manage",
    "marks.enter",
    "marks.moderate",
    "reportcard.generate",
    "reportcard.publish",
    "fee.view",
    "fee.reports",
    "certificate.issue",
    "homework.manage",
    "announcement.send",
    "notification.send",
    "engagement.manage",
    "dashboard.principal",
    "transport.manage",
    "library.manage",
    "hostel.manage",
    "frontoffice.manage",
    "wellbeing.manage",
    "accounting.manage",
    "payroll.manage",
    "inventory.manage",
    "task.manage",
    "lms.manage",
  ],
  ADMIN: [
    "session.manage",
    "student.view",
    "student.edit",
    "student.import",
    "guardian.manage",
    "admission.manage",
    "leave.apply",
    "leave.approve",
    "class.manage",
    "subject.manage",
    "timetable.manage",
    "attendance.mark",
    "attendance.view",
    "attendance.regularize",
    "exam.manage",
    "reportcard.generate",
    "fees.collect",
    "fee.view",
    "certificate.issue",
    "announcement.send",
    "notification.send",
    "engagement.manage",
    "transport.manage",
    "library.manage",
    "hostel.manage",
    "frontoffice.manage",
    "wellbeing.manage",
    "accounting.manage",
    "payroll.manage",
    "inventory.manage",
    "task.manage",
    "lms.manage",
  ],
  ACCOUNTANT: [
    "student.view",
    "leave.apply",
    "fee.setup",
    "fees.collect",
    "fee.view",
    "fee.concession.approve",
    "fee.refund",
    "fee.reports",
    "notification.send",
    "accounting.manage",
    "payroll.manage",
  ],
  TEACHER: [
    "student.view",
    "leave.apply",
    "attendance.mark",
    "attendance.view",
    "marks.enter",
    "homework.manage",
    "lms.manage",
  ],
};
